
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_PlanterPinkEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9037, 1, 0, 5}, {9037, 1, 1, 5}, {9037, 1, 1, 5}// 3	4	5	
			, {3255, 1, 1, 5}, {3255, 1, 0, 5}// 6	7	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_PlanterPinkEAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_PlanterPinkEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 699, 0, 1, 0, 121, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 699, 1, 0, 0, 121, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 697, 1, 1, 0, 121, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 699, 0, 0, 0, 121, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 696, 0, -1, 0, 121, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 698, 1, -1, 0, 121, -1, "", 1);// 11

		}

		public KOT_PlanterPinkEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_PlanterPinkEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_PlanterPinkEAddon();
			}
		}

		[Constructable]
		public KOT_PlanterPinkEAddonDeed()
		{
			Name = "KOT_PlanterPinkE";
		}

		public KOT_PlanterPinkEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}