
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_TVRoomAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4240, -2, -1, 6}, {4552, -2, -2, 1}, {4552, -2, 3, 1}// 1	12	15	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_TVRoomAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_TVRoomAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1801, 3, -1, 1, 1845, -1, "Couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1801, -2, 2, 1, 1854, -1, "Television", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2806, -1, -1, 1, 1845, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1801, 3, 3, 1, 1845, -1, "Couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1801, 2, 3, 1, 1845, -1, "Couch", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1801, 3, 2, 1, 1845, -1, "Couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1801, 3, 1, 1, 1845, -1, "Couch", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1801, 2, -2, 1, 1845, -1, "Couch", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1801, 3, 0, 1, 1845, -1, "Couch", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1801, 3, -2, 1, 1845, -1, "Couch", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1801, -3, 0, 0, 1845, -1, "Television", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1801, -2, -1, 1, 1854, -1, "Television", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2754, 1, 3, 1, 1845, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2809, 0, 3, 1, 1845, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2808, 1, -1, 1, 1845, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2807, 0, -2, 1, 1845, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2756, -1, 3, 1, 1845, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2755, -1, -2, 1, 1845, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2808, 1, 0, 1, 1845, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2808, 1, 1, 1, 1845, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2808, 1, 2, 1, 1845, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2757, 1, -2, 1, 1845, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2750, 0, 2, 1, 1845, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2750, 0, -1, 1, 1845, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2750, 0, 0, 1, 1845, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2750, 0, 1, 1, 1845, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 4976, -2, 2, 16, 1863, -1, "Remote Control", 1);// 30
			AddComplexComponent( (BaseAddon) this, 4240, -1, -1, 8, 0, -1, "On and Off Switch", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1801, -2, 2, 11, 1854, -1, "Television", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1801, -2, 2, 6, 1854, -1, "Television", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1801, -3, 0, 0, 1854, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1801, -2, -1, 11, 1854, -1, "Television", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1801, -2, -1, 6, 1854, -1, "Television", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1801, -3, -1, 0, 1854, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1801, -2, 1, 1, 1854, -1, "Television", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2913, 2, 0, 1, 1845, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2913, 2, 1, 1, 1845, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2913, 2, 2, 1, 1845, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1801, -2, 0, 1, 1854, -1, "Television", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2913, 2, -1, 1, 1845, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 5028, 3, 3, 6, 1845, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 5028, 3, 2, 6, 1845, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 5028, 3, 1, 6, 1845, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 5028, 3, 0, 6, 1845, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 5028, 3, -1, 6, 1845, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 5028, 3, -2, 6, 1845, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 5028, 2, -2, 6, 1845, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 5028, 2, 3, 6, 1845, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 6686, -2, 1, 6, 96, -1, "TV Screen", 1);// 52
			AddComplexComponent( (BaseAddon) this, 6686, -2, 0, 6, 96, -1, "TV Screen", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1801, -3, -1, 0, 1845, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2806, -1, 0, 1, 1845, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2806, -1, 1, 1, 1845, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2806, -1, 2, 1, 1845, -1, "", 1);// 57

		}

		public KOT_TVRoomAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_TVRoomAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_TVRoomAddon();
			}
		}

		[Constructable]
		public KOT_TVRoomAddonDeed()
		{
			Name = "KOT_TVRoom";
		}

		public KOT_TVRoomAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}