
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_MinibarAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {8080, 1, 1, 8}, {8077, 0, 1, 8}, {4095, 2, 1, 8}// 1	3	5	
			, {6467, 2, -1, 6}, {6466, -1, 1, 8}// 9	12	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_MinibarAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_MinibarAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6426, 0, 1, 0, 1164, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6426, -1, 1, 0, 1164, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2602, 1, 2, 0, 1164, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2602, -1, 2, 0, 1164, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2602, 0, 2, 0, 1164, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6424, 2, -1, 0, 1164, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6419, 2, 1, 0, 1164, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6424, 2, 0, 0, 1164, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6426, 1, 1, 0, 1164, -1, "", 1);// 14

		}

		public KOT_MinibarAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_MinibarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_MinibarAddon();
			}
		}

		[Constructable]
		public KOT_MinibarAddonDeed()
		{
			Name = "KOT_Minibar";
		}

		public KOT_MinibarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}