
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_HurstSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2931, 0, -2, 1}, {2931, 0, -1, 1}, {2931, 0, 0, 1}// 1	2	3	
			, {7949, 0, 1, 7}, {3208, 0, 1, 9}, {3244, 1, 0, 1}// 10	11	12	
			, {3378, 1, 0, 1}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_HurstSouthAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_HurstSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4117, -1, -1, 1, 0, -1, "wagon wheel", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4117, 1, -1, 1, 0, -1, "wagon wheel", 1);// 5
			AddComplexComponent( (BaseAddon) this, 5112, -1, 1, 1, 0, -1, "harness", 1);// 6
			AddComplexComponent( (BaseAddon) this, 5112, 0, 1, 0, 0, -1, "harness", 1);// 7
			AddComplexComponent( (BaseAddon) this, 16382, 0, 3, 3, 1175, -1, "Royal Steed", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6361, 0, 0, 12, 32, -1, "A Freshly Picked Rose", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7248, 0, -1, 8, 2260, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7247, 0, -2, 8, 2260, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7249, 0, 0, 8, 2260, -1, "", 1);// 15

		}

		public KOT_HurstSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_HurstSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_HurstSouthAddon();
			}
		}

		[Constructable]
		public KOT_HurstSouthAddonDeed()
		{
			Name = "KOT_HurstSouth";
		}

		public KOT_HurstSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}