
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_GreenWellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3251, 1, 0, 0}, {3244, 1, 0, 0}, {4968, 1, 0, 4}// 1	2	3	
			, {4969, 1, 0, 2}, {10489, 1, 0, 15}, {9327, 1, -1, 0}// 4	5	6	
			, {3248, 1, -1, 0}, {9353, 0, -1, 5}, {9345, 0, -1, 0}// 7	8	9	
			, {9352, -1, -1, 0}, {9353, -1, -1, 5}, {3234, -1, 1, 0}// 10	11	12	
			, {9353, -1, 0, 5}, {10491, 0, 0, 15}, {6039, 0, 0, 0}// 13	14	15	
			, {9353, 0, 0, 5}, {9343, 0, 0, 0}, {3250, 0, 1, 0}// 16	17	18	
			, {3248, 0, 1, 0}, {7840, 0, 1, 4}, {4090, 0, 1, 9}// 19	20	21	
			, {10491, 0, 1, 15}, {3212, 2, 0, 3}, {4973, 1, 1, 4}// 22	23	24	
			, {10489, 1, 1, 15}, {9344, -1, 0, 0}// 25	26	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_GreenWellAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_GreenWellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KOT_GreenWellAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_GreenWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_GreenWellAddon();
			}
		}

		[Constructable]
		public KOT_GreenWellAddonDeed()
		{
			Name = "KOT_GreenWell";
		}

		public KOT_GreenWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}