
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_FlowerLitePostONAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4179, 0, 0, 5}// 8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_FlowerLitePostONAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_FlowerLitePostONAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2852, 0, 0, 1, 0, 29, "Fancy lamp post", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 16, 0, -1, "leaves", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4179, 0, 0, 17, 2337, -1, "morning glories", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 0, 0, -1, "leaves", 2);// 4
			AddComplexComponent( (BaseAddon) this, 6374, 0, 0, 6, 0, -1, "leaves", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4175, 0, 0, 10, 2276, -1, "morning glories", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4175, 0, 0, 2, 2276, -1, "morning glories", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4179, 1, 1, 13, 2337, -1, "morning glories", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3976, 1, 1, 9, 0, -1, "leaves", 1);// 10

		}

		public KOT_FlowerLitePostONAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_FlowerLitePostONAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_FlowerLitePostONAddon();
			}
		}

		[Constructable]
		public KOT_FlowerLitePostONAddonDeed()
		{
			Name = "KOT_FlowerLitePostON";
		}

		public KOT_FlowerLitePostONAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}