
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_CornerFireplaceMarbleAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4551, -1, 2, 7}, {3342, -1, 2, 10}, {1801, -1, -1, 10}// 7	12	15	
			, {3342, -1, 2, 10}, {13371, -1, -1, 0}, {4551, 2, -1, 7}// 21	25	31	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_CornerFireplaceMarbleAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_CornerFireplaceMarbleAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1981, -1, 1, 15, 1, -1, "Fireplace", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1981, -1, 0, 15, 1, -1, "Fireplace", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1981, -1, -1, 15, 1, -1, "Fireplace", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1981, 0, -1, 15, 1, -1, "Fireplace", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1981, 1, -1, 15, 1, -1, "Fireplace", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3342, -1, 2, 10, 2195, -1, "tulips", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1801, -1, 1, 0, 1153, -1, "Fireplace", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2564, -1, 2, 12, 0, 1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1801, 1, -1, 5, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1801, 1, -1, 0, 1153, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3345, -1, 2, 10, 2195, -1, "tulips", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1801, -1, 0, 10, 1153, -1, "Fireplace", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1801, -1, 1, 10, 1153, -1, "Fireplace", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1801, 0, -1, 10, 1153, -1, "Fireplace", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1801, 1, -1, 10, 1153, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 270, 0, 0, 0, 1153, -1, "Fireplace", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1801, -1, 1, 5, 1153, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3332, -1, 2, 10, 0, -1, "leaves", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1981, -1, 2, 5, 1, -1, "Fireplace", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1801, -1, 2, 0, 1153, -1, "Fireplace", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13371, -1, 0, 0, 0, -1, "Embers", 1);// 26
			AddComplexComponent( (BaseAddon) this, 13371, 0, 0, 0, 0, -1, "Embers", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13371, 0, -1, 0, 0, -1, "Embers", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1981, 2, -1, 5, 1, -1, "Fireplace", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1801, 2, -1, 0, 1153, -1, "Fireplace", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3332, 2, -1, 10, 0, -1, "leaves", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3347, 2, -1, 12, 2337, -1, "pansies", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2559, 2, -1, 13, 0, 1, "", 1);// 34

		}

		public KOT_CornerFireplaceMarbleAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_CornerFireplaceMarbleAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_CornerFireplaceMarbleAddon();
			}
		}

		[Constructable]
		public KOT_CornerFireplaceMarbleAddonDeed()
		{
			Name = "KOT_CornerFireplaceMarble";
		}

		public KOT_CornerFireplaceMarbleAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}