
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_LaundrySetEastAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_LaundrySetEastAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_LaundrySetEastAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1801, 0, -1, 11, 1153, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2706, 0, 1, 12, 1165, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2880, 0, 1, 6, 1153, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1801, 0, 0, 11, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1801, 0, -1, 6, 1153, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3835, 0, 0, 22, 0, -1, "downy", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3607, 0, 0, 18, 1165, -1, "Snuggle Dryer Sheets", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3622, 1, 1, 23, 1161, -1, "Tide with Bleach", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2706, 0, 1, 14, 1165, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2706, 0, 1, 13, 1165, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2476, 0, -1, 17, 444, -1, "laundry basket", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3859, 1, 0, 17, 2373, -1, "dial", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3859, 1, -1, 17, 2373, -1, "dial", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7727, 1, 0, 0, 906, -1, "door", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1801, 0, 0, 6, 1153, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7727, 1, -1, 0, 906, -1, "door", 1);// 16

		}

		public KOT_LaundrySetEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_LaundrySetEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_LaundrySetEastAddon();
			}
		}

		[Constructable]
		public KOT_LaundrySetEastAddonDeed()
		{
			Name = "KOT_LaundrySetEast";
		}

		public KOT_LaundrySetEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}