
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_waterWheelAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4117, 0, 1, 1}, {13423, 0, 1, 1}, {13423, 0, 0, 1}// 1	2	3	
			, {13345, 1, 1, 5}, {3232, 1, 2, 10}, {13427, 0, 2, 0}// 4	5	6	
			, {3244, 1, 0, 6}, {3248, 1, 0, 6}, {3252, 2, 1, 9}// 7	8	9	
			, {3205, 2, 1, 18}, {13579, 0, 2, 1}, {3236, 2, 2, 7}// 10	11	12	
			, {13579, 0, 0, 9}, {13595, 0, -1, 1}, {155, -1, 0, 1}// 13	14	15	
			, {165, -1, 1, 1}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_waterWheelAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_waterWheelAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KOT_waterWheelAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_waterWheelAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_waterWheelAddon();
			}
		}

		[Constructable]
		public KOT_waterWheelAddonDeed()
		{
			Name = "KOT_waterWheel";
		}

		public KOT_waterWheelAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}