
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_ArtAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2879, 1, -2, 0}, {3589, 1, -2, 8}, {3942, 1, 1, 0}// 1	2	4	
			, {3589, 1, 1, 9}, {4033, 1, 2, 5}// 5	7	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_ArtAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_ArtAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2575, 1, -2, 10, 0, 2, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2575, 1, 1, 11, 0, 2, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3622, 0, 2, 0, 1161, -1, "Bottle of Paint", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6215, 0, 2, 0, 0, -1, "bottle of paint", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3842, 0, 3, 7, 0, -1, "bottle of paint", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2540, -1, 2, 0, 1153, -1, "Paint Can", 1);// 11

		}

		public KOT_ArtAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_ArtAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_ArtAddon();
			}
		}

		[Constructable]
		public KOT_ArtAddonDeed()
		{
			Name = "KOT_Art";
		}

		public KOT_ArtAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}