
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_BloodRoseDarkVaseBouquetAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_BloodRoseDarkVaseBouquetAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_BloodRoseDarkVaseBouquetAddon()
		{



			AddComplexComponent( (BaseAddon) this, 2886, 0, 0, 0, 1175, -1, "Bouquet of Blood roses", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 1, 0, -1, "foliage", 2);// 2
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 5, 2180, -1, "blood roses", 2);// 3
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 7, 2180, -1, "blood roses", 1);// 4

		}

		public KOT_BloodRoseDarkVaseBouquetAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_BloodRoseDarkVaseBouquetAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_BloodRoseDarkVaseBouquetAddon();
			}
		}

		[Constructable]
		public KOT_BloodRoseDarkVaseBouquetAddonDeed()
		{
			Name = "KOT_BloodRoseDarkVaseBouquet";
		}

		public KOT_BloodRoseDarkVaseBouquetAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}