
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_BridgewithWaterAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {280, -5, -4, 0}, {280, -3, -4, 0}, {3264, -2, -3, 5}// 1	3	6	
			, {3264, -3, -3, 5}, {3264, -4, -3, 5}, {3264, -5, -3, 5}// 7	13	14	
			, {3264, -1, -3, 5}, {2187, 1, 3, 6}, {2187, 1, 2, 6}// 22	23	24	
			, {2187, 1, 1, 6}, {2187, 1, 0, 6}, {2187, 3, 3, 6}// 25	26	43	
			, {2187, 3, 2, 6}, {2187, 3, 1, 6}, {2187, 3, 0, 6}// 44	45	46	
			, {6374, 3, 3, 12}, {6374, 3, 2, 12}, {6374, 3, 1, 12}// 47	48	49	
			, {6374, 3, 0, 12}, {6374, 1, 3, 12}, {6374, 1, 2, 12}// 50	51	52	
			, {6374, 1, 1, 12}, {6374, 1, 0, 12}, {13435, 1, -1, 0}// 53	54	63	
			, {13435, 1, 0, 0}, {13435, 1, 1, 0}, {13435, 1, 2, 0}// 64	65	66	
			, {13435, 1, 3, 0}, {13435, 1, 4, 0}, {13435, 2, -1, 0}// 67	68	69	
			, {13435, 2, 0, 0}, {13435, 2, 1, 0}, {13435, 2, 2, 0}// 70	71	72	
			, {13435, 2, 3, 0}, {13435, 2, 4, 0}, {13435, 2, 5, 0}// 73	74	75	
			, {13435, 3, -1, 0}, {13435, 3, 4, 0}, {13435, 3, 5, 0}// 76	77	78	
			, {13435, 4, -1, 0}, {13435, 4, 4, 0}, {13435, 0, 4, 0}// 79	80	81	
			, {13435, 0, 3, 0}, {13435, 0, 2, 0}, {13435, 0, 1, 0}// 82	83	84	
			, {13435, 0, 0, 0}, {4551, 4, -2, 0}, {4551, 1, -2, 0}// 85	86	87	
			, {4551, 1, 5, 0}, {4551, 4, 5, 0}, {3332, 4, -2, 2}// 88	89	90	
			, {3332, 1, -2, 2}, {3332, 1, 5, 2}, {3332, 4, 5, 2}// 91	92	93	
			, {13423, -4, -1, 0}, {13423, -4, 0, 0}, {13423, -4, 1, 0}// 102	103	104	
			, {13423, -4, 2, 0}, {13423, -4, 3, 0}, {13423, -3, -1, 0}// 105	106	107	
			, {13423, -3, 0, 0}, {13423, -3, 1, 0}, {13423, -3, 2, 0}// 108	109	110	
			, {13423, -3, 3, 0}, {13423, -2, -1, 0}, {13423, -2, 0, 0}// 111	112	113	
			, {13423, -2, 1, 0}, {13423, -2, 2, 0}, {13423, -2, 3, 0}// 114	115	116	
			, {13423, -1, 0, 0}, {13423, -1, 1, 0}, {13423, -1, 2, 0}// 117	118	119	
			, {13423, -1, 3, 0}, {13551, -1, 3, 1}, {13551, -1, 1, 1}// 120	121	122	
			, {13551, -1, 0, 1}, {13552, -1, 2, 1}, {13579, -2, -2, 0}// 123	124	125	
			, {13579, -3, -2, 0}, {13579, -4, -2, 0}, {3518, -3, 1, 1}// 126	127	128	
			, {3237, -1, -1, 0}, {9036, -1, -1, 6}, {3239, -1, 4, 0}// 129	130	131	
			, {3239, -1, -2, 0}, {3206, 0, 5, 0}, {7951, -3, 2, 3}// 138	139	140	
			, {13423, 0, -1, 0}, {3220, -1, 5, 0}, {3220, -5, -1, 0}// 145	146	147	
			, {3203, -2, 4, 0}, {3203, -5, -2, 0}, {3239, -5, 0, 0}// 148	149	150	
			, {3264, 5, -1, 5}, {3264, 5, 0, 5}, {3264, 5, 1, 5}// 157	158	167	
			, {3264, 5, 2, 5}, {3264, 5, 3, 5}, {3264, 5, 4, 5}// 168	177	178	
			, {4179, 5, -2, 5}, {4179, 5, 5, 5}, {3206, -5, 1, 0}// 187	197	205	
			, {3206, -4, 4, 0}, {6811, -3, 4, 0}, {6811, -5, 3, 0}// 206	207	208	
			, {3255, -3, 0, 1}, {3235, -4, 3, 1}, {3144, -3, 2, 1}// 209	210	211	
			, {3517, 4, 1, 0}, {3516, 4, 2, 6}, {13422, 3, 3, 0}// 212	213	214	
			, {13422, 4, 3, 0}, {13422, 3, 2, 0}, {13422, 4, 2, 0}// 215	216	217	
			, {13422, 3, 1, 0}, {13422, 4, 1, 0}, {13422, 4, 0, 0}// 218	219	220	
			, {13422, 3, 0, 0}// 221	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_BridgewithWaterAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_BridgewithWaterAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 280, -4, -4, 0, 1153, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 280, -2, -4, 0, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3237, -2, -3, 1, 1160, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 279, -2, -3, 0, 1153, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 280, -3, -3, 0, 1153, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 281, -4, -3, 0, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3237, -3, -3, 1, 1160, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3237, -4, -3, 1, 1160, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 279, -4, -3, 0, 1153, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 280, -5, -3, 0, 1153, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 281, -6, -3, 0, 1153, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3237, -5, -3, 1, 1160, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 270, -1, -3, 0, 1153, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 271, -1, -4, 0, 1153, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3237, -1, -3, 0, 1160, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1826, 2, 4, 4, 1153, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1826, 3, 4, 4, 1153, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1826, 2, 5, 0, 1153, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1826, 3, 5, 0, 1153, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1828, 2, -1, 5, 1153, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1828, 3, -1, 5, 1153, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1828, 2, -2, 0, 1153, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1828, 3, -2, 0, 1153, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1288, 2, 3, 8, 1153, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1288, 2, 2, 8, 1153, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1288, 2, 1, 8, 1153, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1288, 2, 0, 8, 1153, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1285, 3, 2, 8, 1153, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1285, 3, 3, 8, 1153, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1285, 3, 1, 8, 1153, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1285, 3, 0, 8, 1153, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 3195, 3, 3, 12, 2181, -1, "rose", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3195, 3, 2, 12, 2181, -1, "rose", 1);// 56
			AddComplexComponent( (BaseAddon) this, 3195, 3, 1, 12, 2181, -1, "rose", 1);// 57
			AddComplexComponent( (BaseAddon) this, 3195, 3, 0, 12, 2181, -1, "rose", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3195, 1, 3, 12, 2181, -1, "rose", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3195, 1, 2, 12, 2181, -1, "rose", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3195, 1, 1, 12, 2181, -1, "rose", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3195, 1, 0, 12, 2181, -1, "rose", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3346, 4, -2, 2, 32, -1, "begonias", 1);// 94
			AddComplexComponent( (BaseAddon) this, 3346, 4, 5, 2, 32, -1, "begonias", 1);// 95
			AddComplexComponent( (BaseAddon) this, 3346, 1, 5, 2, 32, -1, "begonias", 1);// 96
			AddComplexComponent( (BaseAddon) this, 3346, 1, -2, 2, 32, -1, "begonias", 1);// 97
			AddComplexComponent( (BaseAddon) this, 3345, 4, 5, 2, 1931, -1, "pansies", 1);// 98
			AddComplexComponent( (BaseAddon) this, 3345, 4, -2, 2, 1931, -1, "pansies", 1);// 99
			AddComplexComponent( (BaseAddon) this, 3345, 1, -2, 2, 1931, -1, "pansies", 1);// 100
			AddComplexComponent( (BaseAddon) this, 3345, 1, 5, 2, 1931, -1, "pansies", 1);// 101
			AddComplexComponent( (BaseAddon) this, 4175, -1, 4, 0, 1258, -1, "flowers", 1);// 132
			AddComplexComponent( (BaseAddon) this, 4175, 0, 4, 10, 1258, -1, "flowers", 1);// 133
			AddComplexComponent( (BaseAddon) this, 4175, 0, 5, 18, 1161, -1, "flowers", 1);// 134
			AddComplexComponent( (BaseAddon) this, 4175, -1, 4, 1, 1161, -1, "flowers", 1);// 135
			AddComplexComponent( (BaseAddon) this, 4175, 0, 4, 8, 1161, -1, "flowers", 1);// 136
			AddComplexComponent( (BaseAddon) this, 4175, 0, 5, 16, 1258, -1, "flowers", 1);// 137
			AddComplexComponent( (BaseAddon) this, 8474, 3, 4, 6, 1462, -1, "Bluejay", 1);// 141
			AddComplexComponent( (BaseAddon) this, 8495, -3, 1, 3, 742, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 9654, -3, 1, 14, 0, -1, "Faerie", 1);// 143
			AddComplexComponent( (BaseAddon) this, 10296, -1, -2, 6, 0, -1, "butterfly", 1);// 144
			AddComplexComponent( (BaseAddon) this, 4175, -5, 0, 0, 1258, -1, "flowers", 1);// 151
			AddComplexComponent( (BaseAddon) this, 4175, -4, 0, 10, 1258, -1, "flowers", 1);// 152
			AddComplexComponent( (BaseAddon) this, 4175, -4, 1, 18, 1161, -1, "flowers", 1);// 153
			AddComplexComponent( (BaseAddon) this, 4175, -5, 0, 1, 1161, -1, "flowers", 1);// 154
			AddComplexComponent( (BaseAddon) this, 4175, -4, 0, 8, 1161, -1, "flowers", 1);// 155
			AddComplexComponent( (BaseAddon) this, 4175, -4, 1, 16, 1258, -1, "flowers", 1);// 156
			AddComplexComponent( (BaseAddon) this, 3237, 5, -1, 1, 1160, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 3237, 5, 0, 1, 1160, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 279, 5, 0, 0, 1153, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 281, 4, 0, 0, 1153, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 282, 4, -2, 0, 1153, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 280, 5, -2, 0, 1153, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 281, 4, -1, 0, 1153, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 281, 5, -1, 0, 1153, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 3237, 5, 1, 1, 1160, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 3237, 5, 2, 1, 1160, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 279, 5, 2, 0, 1153, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 281, 4, 2, 0, 1153, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 282, 4, 0, 0, 1153, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 280, 5, 0, 0, 1153, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 281, 4, 1, 0, 1153, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 281, 5, 1, 0, 1153, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 3237, 5, 3, 1, 1160, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 3237, 5, 4, 1, 1160, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 279, 5, 4, 0, 1153, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 281, 4, 4, 0, 1153, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 282, 4, 2, 0, 1153, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 280, 5, 2, 0, 1153, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 281, 4, 3, 0, 1153, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 281, 5, 3, 0, 1153, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 2852, 5, -2, 1, 0, 29, "Fancy lamp post", 1);// 188
			AddComplexComponent( (BaseAddon) this, 3976, 5, -2, 16, 0, -1, "leaves", 1);// 189
			AddComplexComponent( (BaseAddon) this, 4179, 5, -2, 17, 2337, -1, "morning glories", 1);// 190
			AddComplexComponent( (BaseAddon) this, 3976, 5, -2, 0, 0, -1, "leaves", 2);// 191
			AddComplexComponent( (BaseAddon) this, 6374, 5, -2, 6, 0, -1, "leaves", 1);// 192
			AddComplexComponent( (BaseAddon) this, 4175, 5, -2, 10, 2276, -1, "morning glories", 1);// 193
			AddComplexComponent( (BaseAddon) this, 4175, 5, -2, 2, 2276, -1, "morning glories", 1);// 194
			AddComplexComponent( (BaseAddon) this, 4179, 6, -1, 13, 2337, -1, "morning glories", 1);// 195
			AddComplexComponent( (BaseAddon) this, 3976, 6, -1, 9, 0, -1, "leaves", 1);// 196
			AddComplexComponent( (BaseAddon) this, 2852, 5, 5, 1, 0, 29, "Fancy lamp post", 1);// 198
			AddComplexComponent( (BaseAddon) this, 3976, 5, 5, 16, 0, -1, "leaves", 1);// 199
			AddComplexComponent( (BaseAddon) this, 4179, 5, 5, 17, 2337, -1, "morning glories", 1);// 200
			AddComplexComponent( (BaseAddon) this, 3976, 5, 5, 0, 0, -1, "leaves", 2);// 201
			AddComplexComponent( (BaseAddon) this, 6374, 5, 5, 6, 0, -1, "leaves", 1);// 202
			AddComplexComponent( (BaseAddon) this, 4175, 5, 5, 10, 2276, -1, "morning glories", 1);// 203
			AddComplexComponent( (BaseAddon) this, 4175, 5, 5, 2, 2276, -1, "morning glories", 1);// 204
			AddComplexComponent( (BaseAddon) this, 3530, -1, -1, 0, 1153, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 6009, -5, 4, 0, 2419, -1, "garden rock", 1);// 223
			AddComplexComponent( (BaseAddon) this, 6009, 0, -2, 0, 2419, -1, "garden rock", 1);// 224

		}

		public KOT_BridgewithWaterAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_BridgewithWaterAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_BridgewithWaterAddon();
			}
		}

		[Constructable]
		public KOT_BridgewithWaterAddonDeed()
		{
			Name = "KOT_BridgewithWater";
		}

		public KOT_BridgewithWaterAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}