
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_BedEastBrownAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4555, -2, 3, 13}// 7	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_BedEastBrownAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_BedEastBrownAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5691, -2, 0, 6, 1836, -1, "Her Pillow", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3530, 1, -1, 5, 1737, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 0, 1836, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3530, 0, -1, 5, 1737, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3530, 0, 0, 5, 1737, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3530, -1, 0, 5, 1737, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 5691, -2, 1, 6, 1836, -1, "His Pillow", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 0, 1836, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 0, 1836, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 0, 1836, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 0, 1836, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 0, 1836, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 1, 1836, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 1, 1836, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 1, 1836, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 1, 1836, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 1, 1836, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 1, 1836, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 2, 1836, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 2, 1836, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 2, 1836, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 2, 1836, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 2, 1836, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 2, 1836, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 3, 1836, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 3, 1836, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 3, 1836, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 3, 1836, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 3, 1836, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 3, 1836, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 4, 1836, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 4, 1836, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 4, 1836, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 4, 1836, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 4, 1836, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 4, 1836, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 5, 1836, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 5, 1836, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 5, 1836, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 5, 1836, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 5, 1836, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 5, 1836, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 6, 1836, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 6, 1836, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 6, 1836, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 6, 1836, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 6, 1836, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 6, 1836, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 7, 1836, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 7, 1836, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 7, 1836, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 7, 1836, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 7, 1836, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 7, 1836, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2860, -3, 3, 8, 1836, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2860, -3, 2, 8, 1836, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2860, -3, 1, 8, 1836, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 2860, -3, 0, 8, 1836, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 2860, -3, -1, 8, 1836, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2860, -3, -2, 8, 1836, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 5990, -2, -1, 0, 1836, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 5990, 1, 0, 1, 1836, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 5990, -2, 0, 0, 1836, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 0, 1836, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 5990, -1, 2, 0, 1836, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 5990, -1, 1, 0, 1836, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 5990, -1, 0, 0, 1836, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 5990, -1, -1, 0, 1836, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 5990, 0, 2, 0, 1836, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 5990, 0, 1, 0, 1836, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 5990, 0, 0, 0, 1836, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 0, 1836, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 5990, -2, 0, 3, 1836, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 5990, -2, -1, 3, 1836, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 5990, -1, 2, 3, 1836, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 5990, -1, 1, 3, 1836, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 3, 1836, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 5990, -2, 2, 3, 1836, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 5990, 1, 2, 0, 1836, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 5990, 1, 1, 0, 1836, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 5990, 1, 0, 0, 1836, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 5990, 1, -1, 0, 1836, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 5990, 1, -1, 1, 1836, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 0, 1836, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 5990, 1, 2, 1, 1836, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 1, 1836, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 5990, -1, 2, 1, 1836, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 5990, 0, 2, 1, 1836, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 5990, 0, 1, 1, 1836, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 5990, 0, 0, 1, 1836, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 0, 1836, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 5990, -1, -1, 1, 1836, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 5990, -1, 0, 1, 1836, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 5990, -1, 1, 1, 1836, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 5990, -2, 2, 0, 1836, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 5990, -2, 2, 1, 1836, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 1, 1836, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 5990, -2, 0, 1, 1836, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 5990, 1, 1, 1, 1836, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 5990, -2, -1, 1, 1836, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 5990, -2, 2, 2, 1836, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 2, 1836, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 5990, -2, 0, 2, 1836, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 5990, -2, -1, 2, 1836, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 5990, -1, 2, 2, 1836, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 5990, -1, 1, 2, 1836, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 5990, -1, 0, 2, 1836, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 5990, -1, -1, 2, 1836, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 5990, 0, 2, 2, 1836, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 5990, 0, 1, 2, 1836, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 5990, 0, 0, 2, 1836, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 2, 1836, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 5990, 1, -1, 2, 1836, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 5990, 1, 0, 2, 1836, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 5990, 1, 1, 2, 1836, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 5990, 1, 2, 2, 1836, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 5990, -1, 0, 3, 1836, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 5990, -1, -1, 3, 1836, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 5990, 0, 2, 3, 1836, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 5990, 0, 1, 3, 1836, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 5990, 0, 0, 3, 1836, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 3, 1836, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 5990, 1, 2, 3, 1836, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 5990, 1, 1, 3, 1836, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 5990, 1, 0, 3, 1836, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 5990, 1, -1, 3, 1836, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 5990, -2, 2, 4, 1836, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 5990, -2, 1, 4, 1836, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 5990, -2, 0, 4, 1836, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 5990, -2, -1, 4, 1836, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 5990, -1, 2, 4, 1836, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 5990, -1, 1, 4, 1836, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 5990, -1, 0, 4, 1836, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 5990, -1, -1, 4, 1836, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 5990, 0, 2, 4, 1836, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 5990, 0, 1, 4, 1836, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 5990, 0, 0, 4, 1836, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 5990, 0, -1, 4, 1836, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 5990, 1, 2, 4, 1836, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 5990, 1, 1, 4, 1836, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 5990, 1, 0, 4, 1836, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 5990, 1, -1, 4, 1836, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 3530, 1, 2, 5, 1836, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 3530, 0, 2, 5, 1836, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 3530, -1, 2, 5, 1836, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 3530, -2, 2, 5, 1836, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 3530, -2, 1, 5, 1836, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 3530, -1, 1, 5, 1836, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 3530, 0, 1, 5, 1836, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 3530, 1, 1, 5, 1836, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 3530, 1, 0, 5, 1836, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 3530, 0, 0, 5, 1737, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 3530, -1, 0, 5, 1737, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 3530, -2, 0, 5, 1836, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 3530, -2, -1, 4, 1836, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 3530, -1, -1, 5, 1836, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 3530, 0, -1, 5, 1737, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 3530, 1, -1, 5, 1737, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 3530, -2, -1, 5, 1836, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 6428, -2, -2, 0, 1836, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 6428, -2, 3, 0, 1836, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 2670, 3, 2, 6, 1153, -1, "Guest Blanket", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1801, 2, 2, 0, 1836, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1801, 2, 1, 0, 1836, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1801, 2, 0, 0, 1836, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1801, 2, -1, 0, 1836, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 3530, 1, 0, 5, 1737, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 3530, -1, -1, 5, 1737, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 3530, -2, -1, 5, 1737, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 3530, -2, 0, 5, 1737, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 3530, -2, 1, 5, 1737, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 3530, -1, 1, 5, 1737, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 3530, 0, 1, 5, 1737, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 3530, 1, 1, 5, 1737, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 3530, 1, 2, 5, 1737, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 3530, 0, 2, 5, 1737, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 3530, -1, 2, 5, 1737, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 3530, -1, 2, 4, 1737, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 3530, -2, 2, 5, 1737, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 3530, -2, 2, 5, 1737, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 3530, -1, 2, 5, 1737, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 3530, 0, 2, 5, 1737, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 3530, 1, 2, 5, 1737, -1, "", 1);// 184

		}

		public KOT_BedEastBrownAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_BedEastBrownAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_BedEastBrownAddon();
			}
		}

		[Constructable]
		public KOT_BedEastBrownAddonDeed()
		{
			Name = "KOT_BedEastBrown";
		}

		public KOT_BedEastBrownAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}