
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOTRedWellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10555, 0, 0, 0}, {4970, 1, -1, 0}, {3262, 1, 0, 2}// 1	2	3	
			, {6814, 1, 0, 0}, {4967, 1, 0, 2}, {4973, 1, 0, 0}// 4	5	6	
			, {9181, 1, 0, 15}, {3245, 1, 1, 0}, {9181, 1, 1, 15}// 7	8	9	
			, {3247, -1, 0, 0}, {10562, -1, 0, 5}, {10555, -1, 0, 0}// 10	11	12	
			, {4090, 0, 1, 8}, {9183, 0, 1, 15}, {9183, 0, 0, 15}// 13	14	15	
			, {6039, 0, 0, 0}, {10562, 0, 0, 5}, {10558, 0, 0, 0}// 16	17	18	
			, {7840, 0, 1, 3}, {3245, 0, 1, 0}, {10558, 0, -1, 0}// 19	20	21	
			, {10562, 0, -1, 5}, {3232, -1, 1, 0}, {10562, -1, -1, 5}// 22	23	24	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOTRedWellAddonDeed();
			}
		}

		[ Constructable ]
		public KOTRedWellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KOTRedWellAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOTRedWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOTRedWellAddon();
			}
		}

		[Constructable]
		public KOTRedWellAddonDeed()
		{
			Name = "KOTRedWell";
		}

		public KOTRedWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}