
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_WoodWellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {20, 0, 0, 0}, {6039, 0, 0, 1}, {9, 0, 0, 0}// 1	2	3	
			, {8561, 1, 0, 20}, {8564, 0, 0, 20}, {4963, 1, 0, 0}// 4	5	6	
			, {4973, 1, 0, 6}, {3246, 1, 0, 3}, {3223, 1, -1, 0}// 7	8	9	
			, {3203, -1, 0, 0}, {21, -1, 0, 0}, {9, -1, 0, 0}// 10	11	12	
			, {3244, 1, 1, 0}, {3248, 1, 0, 8}, {3264, 1, 1, 0}// 13	14	15	
			, {8564, 0, 1, 20}, {4090, 0, 1, 13}, {3264, 0, 1, 0}// 16	17	18	
			, {8561, 1, 1, 20}, {9, 0, -1, 0}, {3207, -1, 1, 0}// 19	20	21	
			, {22, 0, -1, 0}, {3223, -1, 1, 0}, {7840, 0, 1, 8}// 22	23	24	
			, {9, -1, -1, 0}// 25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_WoodWellAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_WoodWellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KOT_WoodWellAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_WoodWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_WoodWellAddon();
			}
		}

		[Constructable]
		public KOT_WoodWellAddonDeed()
		{
			Name = "KOT_WoodWell";
		}

		public KOT_WoodWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}