
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_PinicAreaAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1250, -4, 6, 0}, {1250, -4, 2, 0}, {949, 6, -1, 0}// 1	2	3	
			, {949, 6, 3, 0}, {1250, -4, 3, 0}, {1250, -4, 4, 0}// 4	5	6	
			, {1250, -4, 5, 0}, {1250, -3, -3, 0}, {1250, -4, -5, 0}// 7	8	9	
			, {1250, -3, -5, 0}, {1250, -3, -4, 0}, {1250, -3, -1, 0}// 10	11	12	
			, {1250, -3, -2, 0}, {1250, -4, 1, 0}, {949, 6, -2, 0}// 13	14	15	
			, {1250, -4, 0, 0}, {1250, -2, 5, 0}, {1250, 0, -1, 0}// 16	17	18	
			, {1250, 0, -2, 0}, {1250, 0, 1, 0}, {1250, -4, -4, 0}// 19	20	21	
			, {1250, -2, 3, 0}, {1250, -2, 4, 0}, {1250, -4, -3, 0}// 22	23	24	
			, {1250, 1, -3, 0}, {949, 6, 4, 0}, {2931, 2, 2, 0}// 25	26	27	
			, {1250, -4, -1, 0}, {3260, 5, -5, 0}, {3260, 5, -4, 0}// 28	29	30	
			, {3261, 5, -5, 0}, {1250, 1, -5, 0}, {1250, -2, 0, 0}// 32	33	34	
			, {1250, -2, -1, 0}, {1250, -2, -2, 0}, {1250, -2, 2, 0}// 35	36	37	
			, {1250, -2, 1, 0}, {1250, -1, 1, 0}, {1250, -1, 0, 0}// 38	39	40	
			, {1250, 0, 0, 0}, {1250, 1, -4, 0}, {1250, 1, 0, 0}// 41	42	43	
			, {1250, 1, -1, 0}, {1250, 1, -2, 0}, {3261, 5, -4, 0}// 44	45	46	
			, {1250, -3, 1, 0}, {2931, 1, -1, 0}, {1250, -3, 5, 0}// 47	48	49	
			, {193, 5, -4, 0}, {1250, -2, 6, 0}, {1250, -3, 6, 0}// 50	51	52	
			, {948, 2, -6, 0}, {1250, -3, 3, 0}, {1250, 0, -4, 0}// 53	54	55	
			, {1250, 0, -3, 0}, {1250, -3, 0, 0}, {1250, 0, -5, 0}// 56	57	58	
			, {1250, -3, 2, 0}, {1250, -3, 4, 0}, {1250, -1, -1, 0}// 59	60	61	
			, {1250, -1, -2, 0}, {1250, -1, -3, 0}, {1250, -1, -4, 0}// 62	63	64	
			, {1250, -1, -5, 0}, {1250, -2, -5, 0}, {1250, -2, -4, 0}// 65	66	67	
			, {1250, -4, -2, 0}, {1250, -2, -3, 0}, {1250, 1, 1, 0}// 68	69	70	
			, {1250, 1, 2, 0}, {1250, 0, 2, 0}, {1250, -1, 2, 0}// 71	72	73	
			, {1250, -1, 3, 0}, {1250, -1, 4, 0}, {1250, -1, 5, 0}// 74	75	76	
			, {1250, -1, 6, 0}, {1250, 0, 6, 0}, {1250, 0, 5, 0}// 77	78	79	
			, {1250, 0, 4, 0}, {1250, 0, 3, 0}, {1250, 1, 3, 0}// 80	81	82	
			, {1250, 1, 4, 0}, {1250, 1, 5, 0}, {1250, 1, 6, 0}// 83	84	85	
			, {1250, 2, 6, 0}, {1250, 2, 5, 0}, {1250, 2, 4, 0}// 86	87	88	
			, {1250, 2, 3, 0}, {1250, 2, 2, 0}, {1250, 2, 1, 0}// 89	90	91	
			, {1250, 2, 0, 0}, {1250, 2, -1, 0}, {1250, 2, -2, 0}// 92	93	94	
			, {1250, 2, -3, 0}, {1250, 2, -4, 0}, {1250, 2, -5, 0}// 95	96	97	
			, {1250, 3, -5, 0}, {1250, 3, -4, 0}, {1250, 3, -3, 0}// 98	99	100	
			, {1250, 3, -2, 0}, {1250, 3, -1, 0}, {1250, 3, 0, 0}// 101	102	103	
			, {1250, 3, 1, 0}, {1250, 3, 2, 0}, {1250, 3, 3, 0}// 104	105	106	
			, {1250, 3, 4, 0}, {1250, 3, 5, 0}, {1250, 3, 6, 0}// 107	108	109	
			, {1250, 4, 6, 0}, {1250, 4, 5, 0}, {1250, 4, 4, 0}// 110	111	112	
			, {1250, 4, 3, 0}, {1250, 4, 2, 0}, {1250, 4, 1, 0}// 113	114	115	
			, {1250, 4, 0, 0}, {1250, 4, -1, 0}, {1250, 4, -2, 0}// 116	117	118	
			, {1250, 4, -3, 0}, {1250, 4, -4, 0}, {1250, 4, -5, 0}// 119	120	121	
			, {1250, 5, 6, 0}, {1250, 5, 5, 0}, {1250, 5, 4, 0}// 122	123	124	
			, {1250, 5, 3, 0}, {1250, 5, 2, 0}, {1250, 5, 1, 0}// 125	126	127	
			, {1250, 5, 0, 0}, {1250, 5, -1, 0}, {1250, 5, -2, 0}// 128	129	130	
			, {1250, 5, -3, 0}, {12790, 5, -4, 0}, {12790, 6, -5, 0}// 131	132	133	
			, {1822, -3, -2, 0}, {4329, -3, -2, 7}, {1822, -3, -1, 0}// 134	135	136	
			, {2416, -3, -1, 14}, {3530, -3, -1, 6}, {2421, -3, -1, 6}// 137	138	140	
			, {1822, -4, 3, 3}, {1822, -4, 3, 0}, {2518, -4, 3, 8}// 141	142	143	
			, {1822, -4, 2, 4}, {5628, -4, 2, 9}, {1822, -3, 0, 2}// 144	145	146	
			, {1822, -3, 0, 0}, {6467, -3, 0, 4}, {1822, -3, 1, 0}// 147	148	149	
			, {7703, -3, 1, 7}, {3530, -3, 1, 6}, {1822, -4, 1, 2}// 151	152	153	
			, {1822, -4, 1, 6}, {5634, -4, 1, 11}, {1822, -4, 0, 2}// 154	155	156	
			, {2459, -4, 0, 11}, {1822, -4, 0, 6}, {1822, -3, -2, 2}// 157	158	159	
			, {1822, -4, -1, 4}, {5625, -4, -1, 9}, {1822, -4, -2, 3}// 160	161	162	
			, {5637, -4, -2, 7}, {1822, -3, 2, 0}, {7703, -3, 2, 7}// 163	164	166	
			, {3530, -3, 2, 6}, {5111, -3, 3, 9}, {1822, -3, 3, 2}// 167	168	169	
			, {1822, -3, 3, 0}, {2449, -3, 3, 7}, {948, 6, -6, 0}// 170	171	172	
			, {948, 5, -6, 0}, {948, 4, -6, 0}, {948, 3, -6, 0}// 173	174	175	
			, {2879, -4, 6, 0}, {2879, -4, -5, 0}, {948, -1, -6, 0}// 176	177	178	
			, {948, -2, -6, 0}, {948, -3, -6, 0}, {948, -4, -6, 0}// 179	180	181	
			, {949, 6, 6, 0}, {949, 6, 5, 0}, {949, -5, -5, 0}// 182	183	184	
			, {949, -5, -4, 0}, {949, -5, -3, 0}, {949, -5, -2, 0}// 185	186	187	
			, {949, -5, -1, 0}, {949, -5, 0, 0}, {949, -5, 1, 0}// 188	189	190	
			, {949, -5, 2, 0}, {949, -5, 3, 0}, {1250, 6, 6, 0}// 191	192	193	
			, {1250, 6, 5, 0}, {1250, 6, 4, 0}, {1250, 6, 3, 0}// 194	195	196	
			, {1250, 6, 2, 0}, {1250, 6, 1, 0}, {1250, 6, 0, 0}// 197	198	199	
			, {1250, 6, -1, 0}, {1250, 6, -2, 0}, {1250, 6, -3, 0}// 200	201	202	
			, {12790, 5, -5, 0}, {12790, 6, -4, 0}, {193, 6, -4, 0}// 203	204	205	
			, {949, -5, 6, 0}, {949, -5, 5, 0}, {949, -5, 4, 0}// 206	207	208	
			, {5625, -4, -1, 9}, {7138, -3, 4, 0}, {5628, -4, 2, 9}// 209	210	212	
			, {5634, -4, 1, 11}, {5637, -4, -2, 7}, {1822, -4, 3, 0}// 213	214	225	
			, {1822, -4, 0, 6}, {1822, -4, 1, 6}, {1822, -4, -2, 3}// 226	227	229	
			, {1822, -4, -1, 4}, {1822, -4, 0, 2}, {1822, -4, 1, 2}// 230	231	232	
			, {1822, -4, 2, 4}, {1822, -4, 3, 3}, {2929, 2, 3, 0}// 233	234	235	
			, {949, 6, -3, 0}, {2931, 1, 0, 0}, {2931, 2, 0, 0}// 236	237	238	
			, {2931, 2, 1, 0}, {4551, -4, -5, 6}, {4551, -4, 6, 6}// 239	240	246	
			, {3342, -4, 6, 9}, {3342, -4, 6, 9}, {194, 4, -4, 0}// 247	248	252	
			, {194, 4, -5, 0}, {949, 6, -4, 0}, {949, 6, -5, 0}// 253	254	255	
			, {3480, 5, -5, 0}, {3483, 5, -5, 0}, {2928, 1, 3, 0}// 256	257	258	
			, {2930, 2, -1, 0}, {2931, 1, 2, 0}, {2931, 1, 1, 0}// 259	260	261	
			, {2913, 0, 1, 0}, {2912, 0, -1, 0}, {2912, 3, -1, 0}// 262	263	264	
			, {2913, 0, 0, 0}, {2519, -4, -4, 7}, {2519, -4, -4, 8}// 266	267	268	
			, {5637, -4, 5, 6}, {2913, 3, 0, 0}, {2913, 3, 1, 0}// 269	270	271	
			, {2911, 3, 3, 0}, {2913, 3, 2, 0}, {2911, 0, 3, 0}// 272	273	274	
			, {2913, 0, 2, 0}, {4179, 5, 6, 5}, {2451, 2, 3, 13}// 282	283	286	
			, {2519, -4, -4, 6}, {2879, -4, 5, 0}, {2879, -4, -4, 0}// 287	290	291	
			, {948, 3, 7, 0}, {948, 2, 7, 0}, {948, -1, 7, 0}// 292	293	294	
			, {948, -2, 7, 0}, {1250, -4, 7, 0}, {1250, -3, 7, 0}// 295	296	297	
			, {1250, -2, 7, 0}, {1250, -1, 7, 0}, {1250, 0, 7, 0}// 298	299	300	
			, {1250, 1, 7, 0}, {1250, 2, 7, 0}, {1250, 3, 7, 0}// 301	302	303	
			, {1250, 4, 7, 0}, {1250, 5, 7, 0}, {1250, 6, 7, 0}// 304	305	306	
			, {947, 6, 7, 0}, {948, 5, 7, 0}, {948, -3, 7, 0}// 307	308	309	
			, {948, 4, 7, 0}, {948, -4, 7, 0}, {949, -5, 7, 0}// 310	311	312	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_PinicAreaAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_PinicAreaAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5360, -1, -3, 0, 0, -1, "KOT_PinicArea", 1);// 31
			AddComplexComponent( (BaseAddon) this, 4846, -3, -1, 5, 0, 0, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 4846, -3, 1, 5, 0, 0, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 4846, -3, 2, 5, 0, 0, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 7138, -3, 4, 0, 0, -1, "Mesquite Logs", 1);// 211
			AddComplexComponent( (BaseAddon) this, 4846, -3, 2, 5, 0, 1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 4846, -3, 1, 5, 0, 1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 4846, -3, -1, 5, 0, 1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 2518, -4, 3, 8, 0, -1, "Marinade", 1);// 218
			AddComplexComponent( (BaseAddon) this, 6467, -3, 0, 4, 0, -1, "Imported Spices", 1);// 219
			AddComplexComponent( (BaseAddon) this, 3530, -3, 2, 6, 1, -1, "Grill", 1);// 220
			AddComplexComponent( (BaseAddon) this, 3530, -3, 1, 6, 1, -1, "Grill", 1);// 221
			AddComplexComponent( (BaseAddon) this, 3530, -3, -1, 6, 1, -1, "Grill", 1);// 222
			AddComplexComponent( (BaseAddon) this, 7703, -3, 2, 7, 0, -1, "Grilled Salmon", 1);// 223
			AddComplexComponent( (BaseAddon) this, 7703, -3, 1, 7, 0, -1, "Grilled Salmon", 1);// 224
			AddComplexComponent( (BaseAddon) this, 2459, -4, 0, 11, 0, -1, "Cooking Wine", 1);// 228
			AddComplexComponent( (BaseAddon) this, 3332, -4, -5, 9, 0, -1, "leaves", 1);// 241
			AddComplexComponent( (BaseAddon) this, 3346, -4, -5, 15, 1161, -1, "tulips", 1);// 242
			AddComplexComponent( (BaseAddon) this, 3346, -4, -4, 18, 1931, -1, "tulips", 1);// 243
			AddComplexComponent( (BaseAddon) this, 3346, -3, -5, 18, 1931, -1, "tulips", 1);// 244
			AddComplexComponent( (BaseAddon) this, 3346, -3, -4, 21, 1161, -1, "tulips", 1);// 245
			AddComplexComponent( (BaseAddon) this, 3332, -4, 6, 9, 0, -1, "leaves", 1);// 249
			AddComplexComponent( (BaseAddon) this, 3342, -4, 6, 9, 2195, -1, "tulips", 1);// 250
			AddComplexComponent( (BaseAddon) this, 3345, -4, 6, 9, 2195, -1, "tulips", 1);// 251
			AddComplexComponent( (BaseAddon) this, 4175, 5, 6, 10, 2276, -1, "morning glories", 1);// 265
			AddComplexComponent( (BaseAddon) this, 3976, 5, 6, 0, 0, -1, "leaves", 2);// 275
			AddComplexComponent( (BaseAddon) this, 6374, 5, 6, 6, 0, -1, "leaves", 1);// 276
			AddComplexComponent( (BaseAddon) this, 3577, 2, 1, 18, 1165, -1, "carnations", 2);// 277
			AddComplexComponent( (BaseAddon) this, 4175, 5, 6, 2, 2276, -1, "morning glories", 1);// 278
			AddComplexComponent( (BaseAddon) this, 3976, 5, 6, 16, 0, -1, "leaves", 1);// 279
			AddComplexComponent( (BaseAddon) this, 3976, 2, 1, 14, 0, -1, "foliage", 2);// 280
			AddComplexComponent( (BaseAddon) this, 3976, 2, 1, 17, 0, -1, "foliage", 1);// 281
			AddComplexComponent( (BaseAddon) this, 2852, 5, 6, 1, 0, 29, "Fancy lamp post", 1);// 284
			AddComplexComponent( (BaseAddon) this, 4179, 5, 6, 17, 2337, -1, "morning glories", 1);// 285
			AddComplexComponent( (BaseAddon) this, 2886, 2, 1, 13, 1153, -1, "Bouquet of Carnations", 1);// 288
			AddComplexComponent( (BaseAddon) this, 3577, 2, 1, 19, 1462, -1, "carnations", 1);// 289
			AddComplexComponent( (BaseAddon) this, 3976, 6, 7, 9, 0, -1, "leaves", 1);// 313
			AddComplexComponent( (BaseAddon) this, 4179, 6, 7, 13, 2337, -1, "morning glories", 1);// 314

		}

		public KOT_PinicAreaAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_PinicAreaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_PinicAreaAddon();
			}
		}

		[Constructable]
		public KOT_PinicAreaAddonDeed()
		{
			Name = "KOT_PinicArea";
		}

		public KOT_PinicAreaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}