
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_AlienHeartStorageAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_AlienHeartStorageAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_AlienHeartStorageAddon()
		{



			AddComplexComponent( (BaseAddon) this, 7026, 0, 0, 2, 2373, -1, "preservation tube", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 3, 2096, -1, "formaldehyde", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 4, 2096, -1, "formaldehyde", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 5, 2096, -1, "formaldehyde", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 6, 2096, -1, "formaldehyde", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 7, 2096, -1, "formaldehyde", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 8, 2096, -1, "formaldehyde", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 9, 2096, -1, "formaldehyde", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 10, 2096, -1, "formaldehyde", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 11, 2096, -1, "formaldehyde", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 12, 2096, -1, "formaldehyde", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 13, 2096, -1, "formaldehyde", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 14, 2096, -1, "formaldehyde", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3576, 0, 0, 15, 2096, -1, "formaldehyde", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7026, 0, 0, 16, 2373, -1, "preservation tube", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7405, 1, 1, 19, 0, -1, "alien heart", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7026, 0, 0, 0, 2373, -1, "preservation tube", 1);// 17
			AddComplexComponent( (BaseAddon) this, 7026, 0, 0, 17, 2373, -1, "preservation tube", 1);// 18
			AddComplexComponent( (BaseAddon) this, 587, 1, 1, 19, 32, -1, "alien heart", 1);// 19

		}

		public KOT_AlienHeartStorageAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_AlienHeartStorageAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_AlienHeartStorageAddon();
			}
		}

		[Constructable]
		public KOT_AlienHeartStorageAddonDeed()
		{
			Name = "KOT_AlienHeartStorage";
		}

		public KOT_AlienHeartStorageAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}