
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_StoneWellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {64, -1, 0, 5}, {3204, -1, 1, 0}, {6457, 1, 0, 20}// 1	2	3	
			, {4967, 1, 0, 0}, {3247, 1, 0, 0}, {4090, 1, 0, 10}// 4	5	6	
			, {4970, 0, 1, 0}, {3245, 0, 1, 0}, {3272, 1, -1, 0}// 7	8	9	
			, {7840, 1, 0, 6}, {64, -1, -1, 6}, {6457, 1, 1, 20}// 10	11	12	
			, {65, 0, 0, 0}, {64, 0, -1, 5}, {6459, 0, 1, 20}// 13	14	15	
			, {66, 0, -1, 0}, {3214, 1, 1, 0}, {3252, 1, 1, 0}// 16	17	18	
			, {6039, 0, 0, 1}, {64, 0, 0, 5}, {67, -1, 0, 0}// 19	20	21	
			, {6459, 0, 0, 20}// 22	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_StoneWellAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_StoneWellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KOT_StoneWellAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_StoneWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_StoneWellAddon();
			}
		}

		[Constructable]
		public KOT_StoneWellAddonDeed()
		{
			Name = "KOT_StoneWell";
		}

		public KOT_StoneWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}