
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_LivingRoomEastGrayAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4097, 1, 1, 4}, {8077, 1, 1, 4}, {2711, 3, -3, 0}// 9	27	43	
			, {2711, 2, -3, 0}, {2711, 1, -3, 0}, {2711, 0, -3, 0}// 49	50	51	
			, {2711, -1, -3, 0}, {4554, -2, -2, 0}// 52	55	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_LivingRoomEastGrayAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_LivingRoomEastGrayAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1801, -2, 3, 0, 2224, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2769, 0, 3, 0, 2224, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1801, -2, -1, 0, 2224, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1801, -3, 0, 0, 2224, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9403, -3, -2, 10, 0, 1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2777, 2, 4, 0, 2224, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2777, 1, 4, 0, 2224, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2777, 0, 4, 0, 2224, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2776, 3, -1, 0, 2224, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2775, 0, -2, 0, 2224, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2775, 1, -2, 0, 2224, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2775, 2, -2, 0, 2224, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2769, 2, 1, 0, 2224, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2769, 2, 2, 0, 2224, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2769, 2, 3, 0, 2224, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2769, 1, 3, 0, 2224, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2774, -1, -1, 0, 2224, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2772, -1, 4, 0, 2224, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2771, -1, -2, 0, 2224, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2770, 3, 4, 0, 2224, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2776, 3, 3, 0, 2224, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2776, 3, 2, 0, 2224, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2776, 3, 0, 0, 2224, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2776, 3, 1, 0, 2224, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2769, 1, 1, 0, 2224, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2769, 1, 2, 0, 2224, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 5691, -2, 0, 4, 2219, -1, "A Medium Pillow", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2769, 2, 0, 0, 2224, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2769, 2, -1, 0, 2224, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2769, 1, 0, 0, 2224, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2769, 1, -1, 0, 2224, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2860, -2, 2, 0, 2224, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 5690, -2, -1, 5, 2224, -1, "A Big Pillow", 1);// 35
			AddComplexComponent( (BaseAddon) this, 5690, -3, -1, 5, 2224, -1, "A Big Pillow", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2860, -2, 1, 0, 2224, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2860, -2, 0, 0, 2224, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 5690, -3, 2, 5, 2224, -1, "A Big Pillow", 1);// 39
			AddComplexComponent( (BaseAddon) this, 5690, -2, 3, 5, 2224, -1, "A Big Pillow", 1);// 40
			AddComplexComponent( (BaseAddon) this, 5690, -3, 3, 5, 2224, -1, "A Big Pillow", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1801, -3, 3, 0, 2224, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1801, -3, 2, 0, 2224, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 5691, -2, 2, 4, 2219, -1, "A Medium Pillow", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1801, -3, -1, 0, 2224, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2769, 0, -1, 0, 2224, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 5691, -2, 1, 4, 2219, -1, "A Medium Pillow", 1);// 48
			AddComplexComponent( (BaseAddon) this, 5690, -3, 1, 5, 2224, -1, "A Big Pillow", 1);// 53
			AddComplexComponent( (BaseAddon) this, 3760, -3, 4, 9, 1153, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1801, -3, 1, 0, 2224, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 5690, -3, 0, 5, 2224, -1, "A Big Pillow", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2769, 0, 0, 0, 2224, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 10266, 1, 1, 0, 2224, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 2879, -3, 4, 0, 2224, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2879, -3, -2, 0, 2224, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 2769, 0, 2, 0, 2224, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 2769, 0, 1, 0, 2224, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6361, 1, 2, 8, 1158, -1, "A Freshly Picked Rose", 1);// 64
			AddComplexComponent( (BaseAddon) this, 2774, -1, 0, 0, 2224, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 2774, -1, 1, 0, 2224, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 2774, -1, 2, 0, 2224, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 2774, -1, 3, 0, 2224, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 2773, 3, -2, 0, 2224, -1, "", 1);// 69

		}

		public KOT_LivingRoomEastGrayAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_LivingRoomEastGrayAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_LivingRoomEastGrayAddon();
			}
		}

		[Constructable]
		public KOT_LivingRoomEastGrayAddonDeed()
		{
			Name = "KOT_LivingRoomEastGray";
		}

		public KOT_LivingRoomEastGrayAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}