
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_HanginPlantPinkAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2484, 0, 0, 2}, {2484, 0, 0, 1}// 5	6	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_HanginPlantPinkAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_HanginPlantPinkAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5636, 0, 0, 0, 542, -1, "hanging basket", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3208, 0, 0, 3, 0, -1, "flowers", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2485, 0, 0, 4, 328, -1, "petunias", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2484, 0, 0, 6, 14, -1, "petunias", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9900, 0, 0, 11, 0, -1, "hanging flowers", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2485, 0, 0, 3, 1168, -1, "impatients", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2485, 0, 0, 5, 1166, -1, "impatients", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 1, 0, -1, "foliage", 2);// 10

		}

		public KOT_HanginPlantPinkAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_HanginPlantPinkAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_HanginPlantPinkAddon();
			}
		}

		[Constructable]
		public KOT_HanginPlantPinkAddonDeed()
		{
			Name = "KOT_HanginPlantPink";
		}

		public KOT_HanginPlantPinkAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}