
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOTpond1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6054, -1, -2, 0}, {3483, -3, -2, 0}, {3480, -3, -2, 0}// 1	2	3	
			, {3380, 3, 2, 0}, {6055, 3, 2, 0}, {13423, 2, 1, 0}// 4	5	6	
			, {13423, 1, 1, 0}, {13423, 1, 0, 0}, {13423, 1, -1, 0}// 7	8	9	
			, {13423, 0, -1, 0}, {13423, 0, 0, 0}, {13453, 2, 1, 1}// 10	11	12	
			, {3144, -1, -2, 0}, {3144, 2, -2, 0}, {6056, 0, 2, 0}// 13	14	15	
			, {6053, 2, -2, 0}, {6046, 3, 1, 0}, {6045, 3, 0, 0}// 16	17	18	
			, {3204, 3, -1, 0}, {6057, 2, -1, 0}, {3144, 0, 3, 0}// 19	20	21	
			, {3518, 1, -2, 0}, {3235, -1, 2, 0}, {6047, 1, -2, 0}// 22	23	27	
			, {6047, 0, -2, 0}, {6059, 0, 1, 0}, {13423, 2, 0, 0}// 28	29	30	
			, {6056, -1, 1, 0}, {3262, -1, -3, 0}, {6051, -1, -1, 0}// 31	32	33	
			, {6051, -1, 0, 0}, {6050, 1, 2, 0}, {6053, 3, -1, 0}// 34	35	36	
			, {6050, 2, 2, 0}// 37	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOTpond1AddonDeed();
			}
		}

		[ Constructable ]
		public KOTpond1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2914, -2, 1, 0, 1153, -1, "Marble Bench", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2916, -2, 0, 0, 1153, -1, "Marble Bench", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2915, -2, -1, 0, 1153, -1, "Marble Bench", 1);// 26

		}

		public KOTpond1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOTpond1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOTpond1Addon();
			}
		}

		[Constructable]
		public KOTpond1AddonDeed()
		{
			Name = "KOTpond1";
		}

		public KOTpond1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}