
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_PianoBlackAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4006, 0, 0, 6}, {4006, 0, 1, 6}// 2	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_PianoBlackAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_PianoBlackAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2868, 0, 0, 0, 1, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 5397, 0, 0, 7, 1, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5397, 0, 0, 8, 1, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 5397, 0, 0, 9, 1, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7933, -1, 0, 3, 2373, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2868, 0, 1, 0, 1, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 5397, 0, 1, 7, 1, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 5397, 0, 1, 8, 1, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5397, 0, 1, 9, 1, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2868, -1, 1, 0, 1, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 5397, -1, 1, 6, 1, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 5397, -1, 1, 7, 1, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5397, -1, 1, 8, 1, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 5397, 0, 1, 10, 1, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2860, 1, 0, 0, 1, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2860, 1, 1, 0, 1, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2886, 0, 0, 14, 1153, -1, "Bouquet of Carnations", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 15, 0, -1, "foliage", 2);// 20
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 18, 0, -1, "foliage", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 19, 1165, -1, "carnations", 2);// 22
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 20, 1462, -1, "carnations", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3630, -1, 1, 11, 0, 0, "tip jar", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2845, 0, 1, 13, 0, 1, "", 1);// 25

		}

		public KOT_PianoBlackAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_PianoBlackAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_PianoBlackAddon();
			}
		}

		[Constructable]
		public KOT_PianoBlackAddonDeed()
		{
			Name = "KOT_PianoBlack";
		}

		public KOT_PianoBlackAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}