
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_WaterwithBridgeSpeialAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {280, -4, -4, 0}, {280, -2, -4, 0}, {3264, -1, -3, 5}// 1	3	6	
			, {3264, -2, -3, 5}, {3264, -3, -3, 5}, {3264, -4, -3, 5}// 7	13	14	
			, {3264, 0, -3, 5}, {2187, 2, 3, 6}, {2187, 2, 2, 6}// 22	23	24	
			, {2187, 2, 1, 6}, {2187, 2, 0, 6}, {2187, 4, 3, 6}// 25	26	43	
			, {2187, 4, 2, 6}, {2187, 4, 1, 6}, {2187, 4, 0, 6}// 44	45	46	
			, {6374, 4, 3, 12}, {6374, 4, 2, 12}, {6374, 4, 1, 12}// 47	48	49	
			, {6374, 4, 0, 12}, {6374, 2, 3, 12}, {6374, 2, 2, 12}// 50	51	52	
			, {6374, 2, 1, 12}, {6374, 2, 0, 12}, {13435, 2, -1, 0}// 53	54	63	
			, {13435, 2, 0, 0}, {13435, 2, 1, 0}, {13435, 2, 2, 0}// 64	65	66	
			, {13435, 2, 3, 0}, {13435, 2, 4, 0}, {13435, 3, -1, 0}// 67	68	69	
			, {13435, 3, 0, 0}, {13435, 3, 1, 0}, {13435, 3, 2, 0}// 70	71	72	
			, {13435, 3, 3, 0}, {13435, 3, 4, 0}, {13435, 3, 5, 0}// 73	74	75	
			, {13435, 4, -1, 0}, {13435, 4, 4, 0}, {13435, 4, 5, 0}// 76	77	78	
			, {13435, 5, -1, 0}, {13435, 5, 4, 0}, {13435, 1, 2, 0}// 79	80	81	
			, {13435, 1, 1, 0}, {13435, 1, 0, 0}, {4551, 5, -2, 0}// 82	83	84	
			, {4551, 2, -2, 0}, {4551, 2, 5, 0}, {4551, 5, 5, 0}// 85	86	87	
			, {3332, 5, -2, 2}, {3332, 2, -2, 2}, {3332, 2, 5, 2}// 88	89	90	
			, {3332, 5, 5, 2}, {13423, -3, -1, 0}, {13423, -3, 0, 0}// 91	100	101	
			, {13423, -3, 1, 0}, {13423, -3, 2, 0}, {13423, -3, 3, 0}// 102	103	104	
			, {13423, -2, -1, 0}, {13423, -2, 0, 0}, {13423, -2, 1, 0}// 105	106	107	
			, {13423, -2, 2, 0}, {13423, -1, -1, 0}, {13423, -1, 0, 0}// 108	109	110	
			, {13423, -1, 1, 0}, {13423, -1, 2, 0}, {13423, -1, 3, 0}// 111	112	113	
			, {13423, 0, 0, 0}, {13423, 0, 1, 0}, {13423, 0, 2, 0}// 114	115	116	
			, {13423, 0, 3, 0}, {13551, 0, 3, 1}, {13551, 0, 1, 1}// 117	118	119	
			, {13551, 0, 0, 1}, {13552, 0, 2, 1}, {13579, -1, -2, 0}// 120	121	122	
			, {13579, -2, -2, 0}, {13579, -3, -2, 0}, {3518, -2, 1, 1}// 123	124	125	
			, {3237, 0, -1, 0}, {9036, 0, -1, 6}, {3239, 0, 4, 0}// 126	127	128	
			, {3239, 0, -2, 0}, {3206, 1, 5, 0}, {7951, -2, 2, 3}// 135	136	137	
			, {13423, 1, -1, 0}, {3220, 0, 5, 0}, {3220, -4, -1, 0}// 142	143	144	
			, {3203, -1, 4, 0}, {3203, -4, -2, 0}, {3239, -4, 0, 0}// 145	146	147	
			, {3264, 6, -1, 5}, {3264, 6, 0, 5}, {3264, 6, 1, 5}// 154	155	164	
			, {3264, 6, 2, 5}, {3264, 6, 3, 5}, {3264, 6, 4, 5}// 165	174	175	
			, {4179, 6, -2, 5}, {4179, 6, 5, 5}, {3206, -4, 1, 0}// 184	192	200	
			, {3206, -3, 4, 0}, {6811, -2, 4, 0}, {6811, -4, 3, 0}// 201	202	203	
			, {3255, -2, 0, 1}, {3235, -3, 3, 1}, {3144, -2, 2, 1}// 204	205	206	
			, {3517, 5, 1, 0}, {3516, 5, 2, 6}, {13422, 4, 3, 0}// 207	208	209	
			, {13422, 5, 3, 0}, {13422, 4, 2, 0}, {13422, 5, 2, 0}// 210	211	212	
			, {13422, 4, 1, 0}, {13422, 5, 1, 0}, {13422, 5, 0, 0}// 213	214	215	
			, {13422, 4, 0, 0}, {13435, -2, 3, 0}, {13435, 1, 4, 0}// 216	220	221	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_WaterwithBridgeSpeialAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_WaterwithBridgeSpeialAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 280, -3, -4, 0, 1153, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 280, -1, -4, 0, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3237, -1, -3, 1, 1160, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 279, -1, -3, 0, 1153, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 280, -2, -3, 0, 1153, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 281, -3, -3, 0, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3237, -2, -3, 1, 1160, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3237, -3, -3, 1, 1160, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 279, -3, -3, 0, 1153, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 280, -4, -3, 0, 1153, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 281, -5, -3, 0, 1153, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3237, -4, -3, 1, 1160, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 270, 0, -3, 0, 1153, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 271, 0, -4, 0, 1153, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3237, 0, -3, 0, 1160, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1826, 3, 4, 4, 1153, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1826, 4, 4, 4, 1153, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1826, 3, 5, 0, 1153, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1826, 4, 5, 0, 1153, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1828, 3, -1, 5, 1153, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1828, 4, -1, 5, 1153, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1828, 3, -2, 0, 1153, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1828, 4, -2, 0, 1153, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1288, 3, 3, 8, 1153, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1288, 3, 2, 8, 1153, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1288, 3, 1, 8, 1153, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1288, 3, 0, 8, 1153, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1285, 4, 2, 8, 1153, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1285, 4, 3, 8, 1153, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1285, 4, 1, 8, 1153, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1285, 4, 0, 8, 1153, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 3195, 4, 3, 12, 2181, -1, "rose", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3195, 4, 2, 12, 2181, -1, "rose", 1);// 56
			AddComplexComponent( (BaseAddon) this, 3195, 4, 1, 12, 2181, -1, "rose", 1);// 57
			AddComplexComponent( (BaseAddon) this, 3195, 4, 0, 12, 2181, -1, "rose", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3195, 2, 3, 12, 2181, -1, "rose", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3195, 2, 2, 12, 2181, -1, "rose", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3195, 2, 1, 12, 2181, -1, "rose", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3195, 2, 0, 12, 2181, -1, "rose", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3346, 5, -2, 2, 32, -1, "begonias", 1);// 92
			AddComplexComponent( (BaseAddon) this, 3346, 5, 5, 2, 32, -1, "begonias", 1);// 93
			AddComplexComponent( (BaseAddon) this, 3346, 2, 5, 2, 32, -1, "begonias", 1);// 94
			AddComplexComponent( (BaseAddon) this, 3346, 2, -2, 2, 32, -1, "begonias", 1);// 95
			AddComplexComponent( (BaseAddon) this, 3345, 5, 5, 2, 1931, -1, "pansies", 1);// 96
			AddComplexComponent( (BaseAddon) this, 3345, 5, -2, 2, 1931, -1, "pansies", 1);// 97
			AddComplexComponent( (BaseAddon) this, 3345, 2, -2, 2, 1931, -1, "pansies", 1);// 98
			AddComplexComponent( (BaseAddon) this, 3345, 2, 5, 2, 1931, -1, "pansies", 1);// 99
			AddComplexComponent( (BaseAddon) this, 4175, 0, 4, 0, 1258, -1, "flowers", 1);// 129
			AddComplexComponent( (BaseAddon) this, 4175, 1, 4, 10, 1258, -1, "flowers", 1);// 130
			AddComplexComponent( (BaseAddon) this, 4175, 1, 5, 18, 1161, -1, "flowers", 1);// 131
			AddComplexComponent( (BaseAddon) this, 4175, 0, 4, 1, 1161, -1, "flowers", 1);// 132
			AddComplexComponent( (BaseAddon) this, 4175, 1, 4, 8, 1161, -1, "flowers", 1);// 133
			AddComplexComponent( (BaseAddon) this, 4175, 1, 5, 16, 1258, -1, "flowers", 1);// 134
			AddComplexComponent( (BaseAddon) this, 8474, 4, 4, 6, 1462, -1, "Bluejay", 1);// 138
			AddComplexComponent( (BaseAddon) this, 8495, -2, 1, 3, 742, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 9654, -2, 1, 14, 0, -1, "Faerie", 1);// 140
			AddComplexComponent( (BaseAddon) this, 10296, 0, -2, 6, 0, -1, "butterfly", 1);// 141
			AddComplexComponent( (BaseAddon) this, 4175, -4, 0, 0, 1258, -1, "flowers", 1);// 148
			AddComplexComponent( (BaseAddon) this, 4175, -3, 0, 10, 1258, -1, "flowers", 1);// 149
			AddComplexComponent( (BaseAddon) this, 4175, -3, 1, 18, 1161, -1, "flowers", 1);// 150
			AddComplexComponent( (BaseAddon) this, 4175, -4, 0, 1, 1161, -1, "flowers", 1);// 151
			AddComplexComponent( (BaseAddon) this, 4175, -3, 0, 8, 1161, -1, "flowers", 1);// 152
			AddComplexComponent( (BaseAddon) this, 4175, -3, 1, 16, 1258, -1, "flowers", 1);// 153
			AddComplexComponent( (BaseAddon) this, 3237, 6, -1, 1, 1160, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 3237, 6, 0, 1, 1160, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 279, 6, 0, 0, 1153, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 281, 5, 0, 0, 1153, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 282, 5, -2, 0, 1153, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 280, 6, -2, 0, 1153, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 281, 5, -1, 0, 1153, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 281, 6, -1, 0, 1153, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 3237, 6, 1, 1, 1160, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 3237, 6, 2, 1, 1160, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 279, 6, 2, 0, 1153, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 281, 5, 2, 0, 1153, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 282, 5, 0, 0, 1153, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 280, 6, 0, 0, 1153, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 281, 5, 1, 0, 1153, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 281, 6, 1, 0, 1153, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 3237, 6, 3, 1, 1160, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 3237, 6, 4, 1, 1160, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 279, 6, 4, 0, 1153, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 281, 5, 4, 0, 1153, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 282, 5, 2, 0, 1153, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 280, 6, 2, 0, 1153, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 281, 5, 3, 0, 1153, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 281, 6, 3, 0, 1153, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 2852, 6, -2, 1, 0, 29, "Fancy lamp post", 1);// 185
			AddComplexComponent( (BaseAddon) this, 3976, 6, -2, 16, 0, -1, "leaves", 1);// 186
			AddComplexComponent( (BaseAddon) this, 4179, 6, -2, 17, 2337, -1, "morning glories", 1);// 187
			AddComplexComponent( (BaseAddon) this, 3976, 6, -2, 0, 0, -1, "leaves", 2);// 188
			AddComplexComponent( (BaseAddon) this, 6374, 6, -2, 6, 0, -1, "leaves", 1);// 189
			AddComplexComponent( (BaseAddon) this, 4175, 6, -2, 10, 2276, -1, "morning glories", 1);// 190
			AddComplexComponent( (BaseAddon) this, 4175, 6, -2, 2, 2276, -1, "morning glories", 1);// 191
			AddComplexComponent( (BaseAddon) this, 2852, 6, 5, 1, 0, 29, "Fancy lamp post", 1);// 193
			AddComplexComponent( (BaseAddon) this, 3976, 6, 5, 16, 0, -1, "leaves", 1);// 194
			AddComplexComponent( (BaseAddon) this, 4179, 6, 5, 17, 2337, -1, "morning glories", 1);// 195
			AddComplexComponent( (BaseAddon) this, 3976, 6, 5, 0, 0, -1, "leaves", 2);// 196
			AddComplexComponent( (BaseAddon) this, 6374, 6, 5, 6, 0, -1, "leaves", 1);// 197
			AddComplexComponent( (BaseAddon) this, 4175, 6, 5, 10, 2276, -1, "morning glories", 1);// 198
			AddComplexComponent( (BaseAddon) this, 4175, 6, 5, 2, 2276, -1, "morning glories", 1);// 199
			AddComplexComponent( (BaseAddon) this, 3530, 0, -1, 0, 1153, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 6009, -4, 4, 0, 2419, -1, "garden rock", 1);// 218
			AddComplexComponent( (BaseAddon) this, 6009, 1, -2, 0, 2419, -1, "garden rock", 1);// 219

		}

		public KOT_WaterwithBridgeSpeialAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_WaterwithBridgeSpeialAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_WaterwithBridgeSpeialAddon();
			}
		}

		[Constructable]
		public KOT_WaterwithBridgeSpeialAddonDeed()
		{
			Name = "KOT_WaterwithBridgeSpeial";
		}

		public KOT_WaterwithBridgeSpeialAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}