
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_WineBarrelAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_WineBarrelAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_WineBarrelAddon()
		{



			AddComplexComponent( (BaseAddon) this, 4014, 0, 0, 0, 0, -1, "Barrel of Wine", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6375, 0, 0, 3, 0, -1, "grape vine", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6375, 0, 0, 4, 0, -1, "grape vine", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2513, 0, 0, 4, 0, -1, "", 2);// 4
			AddComplexComponent( (BaseAddon) this, 2503, 1, 0, 3, 223, -1, "Harvest Wine", 1);// 5

		}

		public KOT_WineBarrelAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_WineBarrelAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_WineBarrelAddon();
			}
		}

		[Constructable]
		public KOT_WineBarrelAddonDeed()
		{
			Name = "KOT_WineBarrel";
		}

		public KOT_WineBarrelAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}