
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_GatebaseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1801, -1, 1, 0}, {1801, -1, 0, 0}, {1801, -1, -1, 0}// 1	2	3	
			, {1801, 0, -1, 0}, {1801, 0, 0, 0}, {1801, 0, 1, 0}// 4	5	6	
			, {1801, 1, 1, 0}, {1801, 1, 0, 0}, {1801, 1, -1, 0}// 7	8	9	
			, {1802, -1, 2, 0}, {1802, 0, 2, 0}, {1802, 1, 2, 0}// 19	20	21	
			, {1803, 2, -1, 0}, {1803, 2, 0, 0}, {1803, 2, 1, 0}// 22	23	24	
			, {1807, 2, 2, 0}, {1809, -2, 2, 0}, {1805, -2, 1, 0}// 25	26	27	
			, {1805, -2, 0, 0}, {1805, -2, -1, 0}, {1804, -1, -2, 0}// 28	29	30	
			, {1804, 0, -2, 0}, {1804, 1, -2, 0}, {1806, -2, -2, 0}// 31	32	33	
			, {1808, 2, -2, 0}// 34	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_GatebaseAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_GatebaseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4622, -1, -1, 7, 1170, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4623, 0, -1, 7, 1170, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4624, 1, -1, 7, 1170, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 4629, -1, 0, 7, 1170, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 4630, 0, 0, 7, 1170, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 4625, 1, 0, 7, 1170, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 4628, -1, 1, 7, 1170, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4627, 0, 1, 7, 1170, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 4626, 1, 1, 7, 1170, -1, "", 1);// 18

		}

		public KOT_GatebaseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_GatebaseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_GatebaseAddon();
			}
		}

		[Constructable]
		public KOT_GatebaseAddonDeed()
		{
			Name = "KOT_Gatebase";
		}

		public KOT_GatebaseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}