
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_BodyPartsBarrelAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4655, 0, 0, 0}, {7598, 0, 0, 5}, {4653, 1, 0, 0}// 2	8	9	
			, {7587, 1, 1, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_BodyPartsBarrelAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_BodyPartsBarrelAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3703, 0, 0, 0, 2260, -1, "barrel of body parts", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3821, 0, 0, 1, 1782, -1, "", 6);// 3
			AddComplexComponent( (BaseAddon) this, 3613, 0, 0, 2, 1782, -1, "blood", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7407, 0, 0, 4, 1782, -1, "blood", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7407, 0, 0, 3, 1782, -1, "blood", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7407, 0, 0, 5, 1782, -1, "blood", 1);// 7

		}

		public KOT_BodyPartsBarrelAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_BodyPartsBarrelAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_BodyPartsBarrelAddon();
			}
		}

		[Constructable]
		public KOT_BodyPartsBarrelAddonDeed()
		{
			Name = "KOT_BodyPartsBarrel";
		}

		public KOT_BodyPartsBarrelAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}