
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_PlanterboxBlackAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3259, 0, 1, 5}, {105, 0, 0, 0}, {108, -1, 0, 0}// 1	2	3	
			, {3147, 0, 1, 5}, {6811, 0, 1, 8}, {3143, 0, 1, 5}// 6	7	8	
			, {3259, 1, 1, 5}, {3147, 1, 1, 5}, {6811, 1, 1, 7}// 10	12	13	
			, {3143, 1, 1, 5}// 14	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_PlanterboxBlackAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_PlanterboxBlackAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 106, -1, 1, 0, 1, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 105, 0, 1, 0, 1, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 105, 1, 0, 0, 1, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 107, 1, 1, 0, 1, -1, "", 1);// 11

		}

		public KOT_PlanterboxBlackAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_PlanterboxBlackAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_PlanterboxBlackAddon();
			}
		}

		[Constructable]
		public KOT_PlanterboxBlackAddonDeed()
		{
			Name = "KOT_PlanterboxBlack";
		}

		public KOT_PlanterboxBlackAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}