
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KOT_HangingBasketPinkAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KOT_HangingBasketPinkAddonDeed();
			}
		}

		[ Constructable ]
		public KOT_HangingBasketPinkAddon()
		{



			AddComplexComponent( (BaseAddon) this, 5636, 0, 0, 0, 1153, -1, "hanging basket", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 4, 1931, -1, "begonias", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 3, 1166, -1, "begonias", 2);// 3
			AddComplexComponent( (BaseAddon) this, 6373, 0, 0, 1, 0, -1, "foliage", 2);// 4
			AddComplexComponent( (BaseAddon) this, 3976, 0, 0, 1, 0, -1, "", 2);// 5
			AddComplexComponent( (BaseAddon) this, 9900, 0, 0, 9, 1153, -1, "hanging flowers", 1);// 6

		}

		public KOT_HangingBasketPinkAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KOT_HangingBasketPinkAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KOT_HangingBasketPinkAddon();
			}
		}

		[Constructable]
		public KOT_HangingBasketPinkAddonDeed()
		{
			Name = "KOT_HangingBasketPink";
		}

		public KOT_HangingBasketPinkAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}