/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallFishTankLightwoodAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallFishTankLightwoodAddonDeed();
			}
		}

		[ Constructable ]
		public SmallFishTankLightwoodAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13562 );
			AddComponent( ac, 0, 1, 2 );
			ac = new AddonComponent( 13592 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 10 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 9 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 11 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 6 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 12 );
			ac = new AddonComponent( 10651 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 1, 16 );
			ac = new AddonComponent( 10643 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 9 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 2 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 1, 0, 4 );
			ac = new AddonComponent( 10642 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 10643 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3379 );
			AddComponent( ac, 1, 1, 10 );
			ac = new AddonComponent( 4037 );
			AddComponent( ac, 1, 1, 6 );
			ac = new AddonComponent( 3543 );
			AddComponent( ac, 1, 1, 6 );
			ac = new AddonComponent( 13410 );
			ac.Name = "Sand";
			ac.Hue = 345;
			AddComponent( ac, 1, 1, 6 );
		}

		public SmallFishTankLightwoodAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallFishTankLightwoodAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallFishTankLightwoodAddon();
			}
		}

		[Constructable]
		public SmallFishTankLightwoodAddonDeed()
		{
			Name = "A Small Light Wood FishTank Deed";
			Weight = 25;
		}

		public SmallFishTankLightwoodAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}